package com.novoideal.tabuademares.model;

/**
 * Created by Helio on 21/10/2017.
 */

import com.j256.ormlite.field.DatabaseField;

import java.util.Date;

public class SeaCondition {

    // id is generated by the database and set on the object automagically
    @DatabaseField(generatedId = true)
    int id;

    @DatabaseField
    private String city;
    @DatabaseField
    private String uf;
    @DatabaseField
    private String updated;
    @DatabaseField
    private String period;
    @DatabaseField
    private Date date;
    @DatabaseField
    private String agitation;
    @DatabaseField
    private Double height;
    @DatabaseField
    private String sewll;
    @DatabaseField
    private Double wind;
    @DatabaseField
    private String wind_dir;

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getUf() {
        return uf;
    }

    public void setUf(String uf) {
        this.uf = uf;
    }

    public String getUpdated() {
        return updated;
    }

    public void setUpdated(String updated) {
        this.updated = updated;
    }

    public String getPeriod() {
        return period;
    }

    public void setPeriod(String period) {
        this.period = period;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public String getAgitation() {
        return agitation;
    }

    public void setAgitation(String agitation) {
        this.agitation = agitation;
    }

    public Double getHeight() {
        return height;
    }

    public void setHeight(Double height) {
        this.height = height;
    }

    public String getSewll() {
        return sewll;
    }

    public void setSewll(String sewll) {
        this.sewll = sewll;
    }

    public Double getWind() {
        return wind;
    }

    public void setWind(Double wind) {
        this.wind = wind;
    }

    public String getWind_dir() {
        return wind_dir;
    }

    public void setWind_dir(String wind_dir) {
        this.wind_dir = wind_dir;
    }

    @Override
    public String toString() {
        return "";
    }
}